function [fitresult, gof] = FitForceLegs3(time3, F3)
%CREATEFIT(TIME3,F3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : time3
%      Y Output: F3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jun-2021 13:32:19


%% Fit: 'untitled fit 1'.
global DEBUG_FLAG
[xData, yData] = prepareCurveData( time3, F3 );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [2192.93618556523 0.349999999999994 0.276645694160326 1211.08505991301 1.14999999999999 0.311189639078183 787.798470983395 1.69999999999999 0.403932261199806];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if DEBUG_FLAG
    % Create a figure for the plots.
    figure( 'Name', '3Gaussians Force' );

    % Plot fit with data.
    subplot( 2, 1, 1 );
    h = plot( fitresult, xData, yData );
    legend( h, 'F3 vs. time3', '3Gaussians Force', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'time3', 'Interpreter', 'none' );
    ylabel( 'F3', 'Interpreter', 'none' );
    grid on

    % Plot residuals.
    subplot( 2, 1, 2 );
    h = plot( fitresult, xData, yData, 'residuals' );
    legend( h, '3Gaussians Force - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'time3', 'Interpreter', 'none' );
    ylabel( 'F3', 'Interpreter', 'none' );
    grid on

end
